In [49]:
# Dependencies and Setup
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
# Hide warning messages in notebook
import warnings

warnings.filterwarnings('ignore')

# File to Load (Remember to Change These)
# mouse_drug_data_to_load = "../Resources/mouse_drug_data.csv"
# clinical_trial_data_to_load = "Resources/clinicaltrial_data.csv"

# Read the Mouse and Drug Data and the Clinical Trial Data

clinic_data = pd.read_csv("Resources/clinicaltrial_data.csv")
mice_data = pd.read_csv("Resources/mouse_drug_data.csv")
print(type(mice_data))
# Combine the data into a single dataset

# mrg = m_df.merge(c_df, how='left', left_on="Mouse ID", right_on="Mouse ID")

mrg2 = mice_data.merge(clinic_data, how='left', left_on ="Mouse ID", right_on="Mouse ID")

#type(mrg2)

# Display the data table for preview

mrg2

<class 'pandas.core.frame.DataFrame'>

     Mouse ID      Drug  Timepoint  Tumor Volume (mm3)  Metastatic Sites
0        f234  Stelasyn          0           45.000000                 0
1        f234  Stelasyn          5           47.313491                 0
2        f234  Stelasyn         10           47.904324                 0
3        f234  Stelasyn         15           48.735197                 1
4        f234  Stelasyn         20           51.112713                 2
5        f234  Stelasyn         25           52.178602                 2
6        f234  Stelasyn         30           56.873817                 2
7        f234  Stelasyn         35           57.748758                 2
8        x402  Stelasyn          0           45.000000                 0
9        x402  Stelasyn          5           46.327570                 1
10       x402  Stelasyn         10           46.886962                 1
11       x402  Stelasyn         15           49.119948                 1
12       x402  Stelasyn         20           50.414750                 2
13       x402  Stelasyn         25           52.431737                 2
14       x402  Stelasyn         30           54.351585                 3
15       x402  Stelasyn         35           55.240962                 3
16       x402  Stelasyn         40           56.691723                 3
17       x402  Stelasyn         45           61.619606                 3
18       a492  Stelasyn          0           45.000000                 0
19       a492  Stelasyn          5           46.409143                 0
20       a492  Stelasyn         10           48.432197                 0
21       a492  Stelasyn         15           51.985263                 0
22       a492  Stelasyn         20           53.677193                 0
23       a492  Stelasyn         25           54.701229                 1
24       a492  Stelasyn         30           56.201041                 1
25       a492  Stelasyn         35           57.308554                 1
26       a492  Stelasyn         40           57.928499                 1
27       a492  Stelasyn         45           60.122011                 1
28       w540  Stelasyn          0           45.000000                 0
29       w540  Stelasyn          5           45.885370                 1
...       ...       ...        ...                 ...               ...
1876     i669   Placebo         25           53.303185                 2
1877     r850   Placebo          0           45.000000                 0
1878     r850   Placebo          5           46.862912                 0
1879     r850   Placebo         10           48.515091                 1
1880     r850   Placebo         15           50.218605                 1
1881     a262   Placebo          0           45.000000                 0
1882     a262   Placebo          5           48.717568                 1
1883     a262   Placebo         10           49.595181                 1
1884     a262   Placebo         15           53.827974                 2
1885     a262   Placebo         20           57.013313                 2
1886     a262   Placebo         25           60.131862                 2
1887     a262   Placebo         30           64.958092                 3
1888     a262   Placebo         35           66.561963                 4
1889     a262   Placebo         40           69.592732                 4
1890     a262   Placebo         45           70.717621                 4
1891     q787   Placebo          0           45.000000                 0
1892     q787   Placebo          5           47.116616                 0
1893     q787   Placebo         10           48.593862                 1
1894     q787   Placebo         15           49.217732                 2
1895     q787   Placebo         20           50.229934                 2
1896     q787   Placebo         25           52.713188                 2
1897     q787   Placebo         30           55.036206                 2
1898     q787   Placebo         35           60.333852                 3
1899     q787   Placebo         40           62.034127                 3
1900     q787   Placebo         45           66.096475                 3
1901     j235   Placebo          0           45.000000                 0
1902     j235   Placebo          5           46.588820                 0
1903     j235   Placebo         10           48.018788                 1
1904     j235   Placebo         15           51.161138                 1
1905     j235   Placebo         20           52.942902                 1

[1906 rows x 5 columns]

## Tumor Response to Treatment

In [55]:
# Store the Mean Tumor Volume Data Grouped by Drug and Timepoint 

# Convert to DataFrame

# Preview DataFrame

In [56]:
mrg.groupby(['Drug', 'Timepoint']).mean()
final_df = mrg.groupby(['Drug', 'Timepoint']).mean()
final_df

                     Tumor Volume (mm3)  Metastatic Sites
Drug      Timepoint
Capomulin 0                   45.000000          0.000000
          5                   44.266086          0.160000
          10                  43.084291          0.320000
          15                  42.064317          0.375000
          20                  40.716325          0.652174
          25                  39.939528          0.818182
          30                  38.769339          1.090909
          35                  37.816839          1.181818
          40                  36.958001          1.380952
          45                  36.236114          1.476190
Ceftamin  0                   45.000000          0.000000
          5                   46.503051          0.380952
          10                  48.285125          0.600000
          15                  50.094055          0.789474
          20                  52.157049          1.111111
          25                  54.287674          1.500000
          30                  56.769517          1.937500
          35                  58.827548          2.071429
          40                  61.467895          2.357143
          45                  64.132421          2.692308
Infubinol 0                   45.000000          0.000000
          5                   47.062001          0.280000
          10                  49.403909          0.666667
          15                  51.296397          0.904762
          20                  53.197691          1.050000
          25                  55.715252          1.277778
          30                  58.299397          1.588235
          35                  60.742461          1.666667
          40                  63.162824          2.100000
          45                  65.755562          2.111111
...                                 ...               ...
Ramicane  0                   45.000000          0.000000
          5                   43.944859          0.120000
          10                  42.531957          0.250000
          15                  41.495061          0.333333
          20                  40.238325          0.347826
          25                  38.974300          0.652174
          30                  38.703137          0.782609
          35                  37.451996          0.952381
          40                  36.574081          1.100000
          45                  34.955595          1.250000
Stelasyn  0                   45.000000          0.000000
          5                   47.527452          0.240000
          10                  49.463844          0.478261
          15                  51.529409          0.782609
          20                  54.067395          0.952381
          25                  56.166123          1.157895
          30                  59.826738          1.388889
          35                  62.440699          1.562500
          40                  65.356386          1.583333
          45                  68.438310          1.727273
Zoniferol 0                   45.000000          0.000000
          5                   46.851818          0.166667
          10                  48.689881          0.500000
          15                  50.779059          0.809524
          20                  53.170334          1.294118
          25                  55.432935          1.687500
          30                  57.713531          1.933333
          35                  60.089372          2.285714
          40                  62.916692          2.785714
          45                  65.960888          3.071429

[100 rows x 2 columns]

In [ ]:
# Store the Standard Error of Tumor Volumes Grouped by Drug and Timepoint

# Convert to DataFrame

# Preview DataFrame

In [ ]:
# Minor Data Munging to Re-Format the Data Frames

# Preview that Reformatting worked

In [ ]:
# Generate the Plot (with Error Bars)

# Save the Figure

In [ ]:
# Show the Figure
plt.show()

![Tumor Response to Treatment](../Images/treatment.png)

## Metastatic Response to Treatment

In [ ]:
# Store the Mean Met. Site Data Grouped by Drug and Timepoint 

# Convert to DataFrame

# Preview DataFrame

In [ ]:
# Store the Standard Error associated with Met. Sites Grouped by Drug and Timepoint 

# Convert to DataFrame

# Preview DataFrame

In [ ]:
# Minor Data Munging to Re-Format the Data Frames

# Preview that Reformatting worked

In [ ]:
# Generate the Plot (with Error Bars)

# Save the Figure

# Show the Figure

![Metastatic Spread During Treatment](../Images/spread.png)

## Survival Rates

In [ ]:
# Store the Count of Mice Grouped by Drug and Timepoint (W can pass any metric)

# Convert to DataFrame

# Preview DataFrame

In [ ]:
# Minor Data Munging to Re-Format the Data Frames

# Preview the Data Frame

In [ ]:
# Generate the Plot (Accounting for percentages)

# Save the Figure

# Show the Figure
plt.show()

![Metastatic Spread During Treatment](../Images/survival.png)

## Summary Bar Graph

In [ ]:
# Calculate the percent changes for each drug

# Display the data to confirm

In [ ]:
# Store all Relevant Percent Changes into a Tuple


# Splice the data between passing and failing drugs


# Orient widths. Add labels, tick marks, etc. 


# Use functions to label the percentages of changes


# Call functions to implement the function calls


# Save the Figure


# Show the Figure
fig.show()

![Metastatic Spread During Treatment](../Images/change.png)